apiVersion: apps/v1
kind: Deployment
metadata:
  name: actix-devops-web
  namespace: actix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: actix-devops-web
  template:
    metadata:
      labels:
        app: actix-devops-web
    spec:
      containers:
      - name: actix-devops-web
        image: inwerejosic/actix-devops-web:latest
        ports:
        - containerPort: 8080
