version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: actix-devops-web
    container_name: actix-devops-web
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15.3-alpine
    container_name: actix-devops-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
