version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: actix-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  actix-devops-web:
    build:
      context: ./   # path to your Actix Dockerfile
    container_name: actix-devops-web-v2
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    ports:
      - "8080:8080"

volumes:
  pgdata:
