apiVersion: apps/v1
kind: Deployment
metadata:
  name: actix-devops-web-postgres
  namespace: actix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actix-devops-web-postgres
  template:
    metadata:
      labels:
        app: actix-devops-web-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15.3-alpine
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_DB
            value: postgres
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: actix-devops-web-postgres
  namespace: actix
spec:
  selector:
    app: actix-devops-web-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
