apiVersion: v1
kind: Service
metadata:
  name: actix-devops-web
  namespace: actix
spec:
  selector:
    app: my-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
