replicaCount: 1

image:
  repository: inwerejosic/actix-devops-web
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

env:
  - name: DATABASE_URL
    value: postgres://postgres:postgres@actix-postgres:5432/postgres

resources: {}
